# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- '*'

steps:
- script: ls
  displayName: 'List all files/directories in root'

- script: find . -name '*.pshproj' -delete
  displayName: 'Delete pshproj files'

- script: find . -name '*.pssproj' -delete
  displayName: 'Delete pssproj files'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Microsoft.Xrm.Data.PowerShell'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Microsoft.Xrm.Data.PowerShell_$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true