# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- '*'

steps:
- script: ls *
  displayName: 'Run a one-line script'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

- task: CopyPublishBuildArtifacts@1
  displayName: 'Copy Publish Artifact: $(artifactName.ContentDelivery)'
  inputs:
    CopyRoot: "$(Build.StagingDirectory)"
    Contents: "**\\*"
    ArtifactName: "$(artifactName.ContentDelivery)"
    ArtifactType: FilePath
    TargetPath: "\\\\$(Agent.Machinename)\\_drop\\$(octo.PackagePrefix)\\$(Build.BuildId)"